### ISSUE TITLE
Scrabble - Character bonus not applied

### ISSUE THREAD

**Issue by cboki** [kamilmielnik/scrabble-solver#112] opened 2021-04-07 12:22 UTC
Hi folks ! 
I am beginner in web development and I just found your awesome project. I am super excited in adapting it for playing scrabble.

However, it seems that the app doesn't take into account the double/triple letters tiles. Is that correct ?
Here is an example where the score doesn't change (24 points) when the word is moving between the two positions.
Thank you guys for your answer !!

First position : ( 8 + 1 + 1 + 1 +1 ) x 2 = 24 points. I agree with that.
Second position : ( 8x2 + 1 + 1 + 1 +1 ) x 2 => should be 40 points in my opinion.

![Capture d’écran 2021-04-07 141516](https://user-images.githubusercontent.com/16156817/113865426-5caddf80-97ac-11eb-8111-df92f715326e.png)

![Capture d’écran 2021-04-07 141448](https://user-images.githubusercontent.com/16156817/113865437-5e77a300-97ac-11eb-8691-2ee02b63926a.png)

**Comment by kamilmielnik** [comment] 2021-04-07 12:40
Indeed, you've found a bug!

I believe the problem is here: https://github.com/kamilmielnik/scrabble-solver/blob/fdca052f4401c85f792a5cee177626e4cf3fb74c/packages/types/src/CharacterBonus.ts#L16

I think when `this.score` is `undefined`, this function should return `true`.

@cboki  Would you like to submit a PR?

**Comment by kamilmielnik** [comment] 2021-04-07 20:03
Fixed by https://github.com/kamilmielnik/scrabble-solver/pull/113

**Closed by kamilmielnik** 2021-04-07 20:03 UTC
Labels: Priority - Must have, Size - S, Type - Bug

**Comment by kamilmielnik** [comment] 2021-04-07 20:12
Released in [2.4.8](https://github.com/kamilmielnik/scrabble-solver/releases/tag/2.4.8) and deployed at https://scrabble-solver.kamilmielnik.com/ :heavy_check_mark:
